/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react';
import { Document, Page as PdfPage, Text, View as PdfView, StyleSheet, Link, Font } from '@react-pdf/renderer';
import { localized } from '@/lib/helpers';

// @react-pdf/renderer's types reject conditional JSX children (false | Element).
// Thin wrappers widen the children prop to accept standard React patterns.
const Page = PdfPage as React.ComponentType<any>;
const View = PdfView as React.ComponentType<any>;

/* ------------------------------------------------------------------ */
/*  Register Noto Sans TC for CJK support (zh, ja, ko)                */
/*  @react-pdf/renderer supports .ttf, .otf, and .woff (not woff2)    */
/* ------------------------------------------------------------------ */
const NOTO_BASE = 'https://cdn.jsdelivr.net/npm/@fontsource/noto-sans-tc@latest/files';

Font.register({
  family: 'NotoSansCJK',
  fonts: [
    { src: `${NOTO_BASE}/noto-sans-tc-chinese-traditional-400-normal.woff`, fontWeight: 400 },
    { src: `${NOTO_BASE}/noto-sans-tc-chinese-traditional-700-normal.woff`, fontWeight: 700 },
  ],
});

// Disable hyphenation for CJK text
Font.registerHyphenationCallback((word) => [word]);

const gold = '#C8A84E';
const dark = '#0A0A0A';
const muted = '#999';

const styles = StyleSheet.create({
  page: { padding: 40, backgroundColor: '#FFFFFF' },
  header: { marginBottom: 24, borderBottomWidth: 2, borderBottomColor: gold, paddingBottom: 16 },
  name: { fontSize: 28, fontWeight: 'bold', color: dark, marginBottom: 4 },
  subtitle: { fontSize: 12, color: muted },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: gold, marginBottom: 8, textTransform: 'uppercase' as const, letterSpacing: 1 },
  text: { fontSize: 10, color: '#333', lineHeight: 1.5 },
  row: { flexDirection: 'row' as const, marginBottom: 4 },
  label: { fontSize: 10, color: muted, width: 100 },
  value: { fontSize: 10, color: dark, flex: 1 },
  eventRow: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, marginBottom: 6, paddingBottom: 4, borderBottomWidth: 0.5, borderBottomColor: '#eee' },
  eventTitle: { fontSize: 10, color: dark, flex: 1 },
  eventDate: { fontSize: 9, color: muted, width: 80, textAlign: 'right' as const },
  gearRow: { marginBottom: 6 },
  gearName: { fontSize: 10, fontWeight: 'bold', color: dark },
  gearDetail: { fontSize: 9, color: muted },
  footer: { position: 'absolute' as const, bottom: 30, left: 40, right: 40, borderTopWidth: 1, borderTopColor: '#eee', paddingTop: 8, flexDirection: 'row' as const, justifyContent: 'space-between' as const },
  footerText: { fontSize: 8, color: muted },
  link: { fontSize: 10, color: gold, textDecoration: 'none' as const },
});

/* ------------------------------------------------------------------ */
/*  i18n labels for EPK sections                                      */
/* ------------------------------------------------------------------ */
const labels: Record<string, Record<string, string>> = {
  en: {
    biography: 'Biography',
    links: 'Links',
    performances: 'Upcoming Performances',
    gear: 'Gear & Equipment',
    teaching: 'Teaching',
    lessonRates: 'Lesson rates',
    hire: 'Available for Hire',
    premiumArtist: 'Premium Artist',
    footer: 'Electronic Press Kit',
    generatedBy: 'Generated by JazzNode',
  },
  zh: {
    biography: '簡介',
    links: '連結',
    performances: '近期演出',
    gear: '器材與設備',
    teaching: '教學',
    lessonRates: '課程費用',
    hire: '可預約演出',
    premiumArtist: 'Premium 藝人',
    footer: '電子宣傳資料',
    generatedBy: '由 JazzNode 產生',
  },
  ja: {
    biography: 'バイオグラフィー',
    links: 'リンク',
    performances: '今後の公演',
    gear: '機材・設備',
    teaching: 'レッスン',
    lessonRates: 'レッスン料金',
    hire: '出演依頼可',
    premiumArtist: 'プレミアムアーティスト',
    footer: 'エレクトロニック・プレスキット',
    generatedBy: 'JazzNode が生成',
  },
  ko: {
    biography: '약력',
    links: '링크',
    performances: '공연 일정',
    gear: '장비',
    teaching: '레슨',
    lessonRates: '레슨 비용',
    hire: '섭외 가능',
    premiumArtist: '프리미엄 아티스트',
    footer: '전자 프레스 킷',
    generatedBy: 'JazzNode 에서 생성',
  },
};

function t(locale: string, key: string): string {
  return labels[locale]?.[key] || labels.en[key] || key;
}

/* Date locale mapping for toLocaleDateString */
const dateLocaleMap: Record<string, string> = {
  en: 'en-US',
  zh: 'zh-TW',
  ja: 'ja-JP',
  ko: 'ko-KR',
  th: 'th-TH',
  id: 'id-ID',
};

interface EPKProps {
  artist: Record<string, unknown>;
  gear: { gear_name: string; gear_type: string; brand?: string; model?: string }[];
  events: { title_en: string; title_local?: string; start_at: string }[];
  tier: number;
  locale?: string;
}

export function buildEPKDocument({ artist, gear, events, tier, locale = 'en' }: EPKProps) {
  const lang = locale.slice(0, 2); // normalize e.g. 'zh-TW' → 'zh'

  // Localized artist content with fallback
  const name = (localized(artist as Record<string, unknown>, 'name', lang) || artist.display_name || artist.name_en || artist.artist_id) as string;
  const bio = (localized(artist as Record<string, unknown>, 'bio', lang) || '') as string;
  const instrument = (artist.primary_instrument || '') as string;
  const country = (artist.country_code || '') as string;

  const teachingDesc = localized(artist as Record<string, unknown>, 'teaching_description', lang) || '';
  const hireDesc = localized(artist as Record<string, unknown>, 'hire_description', lang) || '';

  const socialLinks: { label: string; url: string }[] = [];
  if (artist.website_url) socialLinks.push({ label: 'Website', url: artist.website_url as string });
  if (artist.spotify_url) socialLinks.push({ label: 'Spotify', url: artist.spotify_url as string });
  if (artist.youtube_url) socialLinks.push({ label: 'YouTube', url: artist.youtube_url as string });
  if (artist.instagram) socialLinks.push({ label: 'Instagram', url: `https://instagram.com/${artist.instagram}` });

  const dateLocale = dateLocaleMap[lang] || 'en-US';
  const cjkLocales = ['zh', 'ja', 'ko'];
  const fontFamily = cjkLocales.includes(lang) ? 'NotoSansCJK' : 'Helvetica';

  return (
    <Document>
      <Page size="A4" style={{ ...styles.page, fontFamily }}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.name}>{name}</Text>
          <Text style={styles.subtitle}>
            {[instrument, country].filter(Boolean).join(' · ')}
            {tier >= 2 ? ` · ${t(lang, 'premiumArtist')}` : ''}
          </Text>
        </View>

        {/* Bio */}
        {bio && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{t(lang, 'biography')}</Text>
            <Text style={styles.text}>{bio}</Text>
          </View>
        )}

        {/* Social Links */}
        {socialLinks.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{t(lang, 'links')}</Text>
            {socialLinks.map((l, i) => (
              <View key={i} style={styles.row}>
                <Text style={styles.label}>{l.label}</Text>
                <Link style={styles.link} src={l.url}>{l.url}</Link>
              </View>
            ))}
          </View>
        )}

        {/* Upcoming Events */}
        {events.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{t(lang, 'performances')}</Text>
            {events.map((e, i) => {
              const title = (lang !== 'en' && e.title_local) ? e.title_local : e.title_en;
              return (
                <View key={i} style={styles.eventRow}>
                  <Text style={styles.eventTitle}>{title}</Text>
                  <Text style={styles.eventDate}>
                    {new Date(e.start_at).toLocaleDateString(dateLocale, { month: 'short', day: 'numeric', year: 'numeric' })}
                  </Text>
                </View>
              );
            })}
          </View>
        )}

        {/* Gear (Tier 2 only) */}
        {tier >= 2 && gear.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{t(lang, 'gear')}</Text>
            {gear.map((g, i) => (
              <View key={i} style={styles.gearRow}>
                <Text style={styles.gearName}>{g.gear_name}</Text>
                <Text style={styles.gearDetail}>
                  {[g.brand, g.model].filter(Boolean).join(' · ') || g.gear_type}
                </Text>
              </View>
            ))}
          </View>
        )}

        {/* Teaching (if accepting students) */}
        {artist.accepting_students && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{t(lang, 'teaching')}</Text>
            {teachingDesc && (
              <Text style={styles.text}>{teachingDesc}</Text>
            )}
            {artist.lesson_price_range && (
              <View style={{ ...styles.row, marginTop: 4 }}>
                <Text style={styles.label}>{t(lang, 'lessonRates')}</Text>
                <Text style={styles.value}>{artist.lesson_price_range as string}</Text>
              </View>
            )}
          </View>
        )}

        {/* Hire info (Tier 2) */}
        {tier >= 2 && artist.available_for_hire && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{t(lang, 'hire')}</Text>
            {hireDesc && (
              <Text style={styles.text}>{hireDesc}</Text>
            )}
          </View>
        )}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>{t(lang, 'footer')} · {name}</Text>
          <Text style={styles.footerText}>{t(lang, 'generatedBy')} · {new Date().toLocaleDateString(dateLocale)}</Text>
        </View>
      </Page>
    </Document>
  );
}
